/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anthony Giron
 */
public class frm_personas extends javax.swing.JFrame {
Cliente cliente;
DefaultTableModel tbl_model;
    /**
     * Creates new form frm_personas
     */
    public frm_personas() {
        initComponents();
        cliente = new Cliente();
        tbl_model = new DefaultTableModel();
        String encabezado [] = {"nit","nombres","apellidos","direccion","telefono","FechaNacimiento"};
            tbl_model.setColumnIdentifiers(encabezado);
            tbl_clientes.setModel(tbl_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_principal = new javax.swing.JTabbedPane();
        pn_clientes = new javax.swing.JPanel();
        lbl_titulo_clientes = new javax.swing.JLabel();
        lbl_nit = new javax.swing.JLabel();
        tf_nit = new javax.swing.JTextField();
        lbl_nombres = new javax.swing.JLabel();
        tf_nombres = new javax.swing.JTextField();
        lbl_apellidos = new javax.swing.JLabel();
        tf_apellidos = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        tf_direccion = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        tf_telefono = new javax.swing.JTextField();
        lbl_fdn = new javax.swing.JLabel();
        tf_fdn = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        spn_tabla = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        btn_modificar = new javax.swing.JButton();
        pn_empleados = new javax.swing.JPanel();
        lbl_titulo_empleados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_clientes.setBackground(new java.awt.Color(204, 204, 204));
        pn_clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_titulo_clientes.setFont(new java.awt.Font("Segoe UI Variable", 1, 48)); // NOI18N
        lbl_titulo_clientes.setText("Formulario Clientes");

        lbl_nit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_nit.setText("NIT");
        lbl_nit.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_nit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tf_nit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_nit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nitActionPerformed(evt);
            }
        });

        lbl_nombres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_nombres.setText("NOMBRES");
        lbl_nombres.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_nombres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tf_nombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_nombres.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombresActionPerformed(evt);
            }
        });

        lbl_apellidos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_apellidos.setText("APELLIDOS");
        lbl_apellidos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_apellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tf_apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_apellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_apellidosActionPerformed(evt);
            }
        });

        lbl_direccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_direccion.setText("DIRECCION");
        lbl_direccion.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tf_direccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_direccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_direccionActionPerformed(evt);
            }
        });

        lbl_telefono.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_telefono.setText("TELEFONO");
        lbl_telefono.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tf_telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefonoActionPerformed(evt);
            }
        });

        lbl_fdn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_fdn.setText("FECHA DE NACIMIENTO");
        lbl_fdn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        lbl_fdn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tf_fdn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_fdn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_fdn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_fdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fdnActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(153, 153, 153));
        btn_guardar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_guardar.setText("CREAR");
        btn_guardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        tbl_clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spn_tabla.setViewportView(tbl_clientes);

        btn_modificar.setBackground(new java.awt.Color(153, 153, 153));
        btn_modificar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_modificar.setText("MODIFICAR");
        btn_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_clientesLayout = new javax.swing.GroupLayout(pn_clientes);
        pn_clientes.setLayout(pn_clientesLayout);
        pn_clientesLayout.setHorizontalGroup(
            pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spn_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                    .addGroup(pn_clientesLayout.createSequentialGroup()
                        .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fdn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_telefono)
                            .addComponent(lbl_direccion)
                            .addComponent(lbl_apellidos)
                            .addComponent(lbl_nit)
                            .addComponent(lbl_nombres))
                        .addGap(36, 36, 36)
                        .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_clientesLayout.createSequentialGroup()
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_fdn, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_apellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(tf_direccion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_telefono, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pn_clientesLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(lbl_titulo_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_clientesLayout.setVerticalGroup(
            pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clientesLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lbl_titulo_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_clientesLayout.createSequentialGroup()
                        .addComponent(lbl_nit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_nombres))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_clientesLayout.createSequentialGroup()
                        .addComponent(tf_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_apellidos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_clientesLayout.createSequentialGroup()
                        .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_direccion))
                        .addGap(14, 14, 14)
                        .addComponent(lbl_telefono))
                    .addComponent(tf_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fdn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_fdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(spn_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tp_principal.addTab("Clientes", pn_clientes);

        lbl_titulo_empleados.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lbl_titulo_empleados.setForeground(new java.awt.Color(153, 153, 0));
        lbl_titulo_empleados.setText("Formulario Empleados");

        javax.swing.GroupLayout pn_empleadosLayout = new javax.swing.GroupLayout(pn_empleados);
        pn_empleados.setLayout(pn_empleadosLayout);
        pn_empleadosLayout.setHorizontalGroup(
            pn_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_empleadosLayout.createSequentialGroup()
                .addContainerGap(662, Short.MAX_VALUE)
                .addComponent(lbl_titulo_empleados)
                .addGap(223, 223, 223))
        );
        pn_empleadosLayout.setVerticalGroup(
            pn_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empleadosLayout.createSequentialGroup()
                .addComponent(lbl_titulo_empleados)
                .addGap(0, 634, Short.MAX_VALUE))
        );

        tp_principal.addTab("Empleados", pn_empleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tp_principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tp_principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nitActionPerformed

    private void tf_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombresActionPerformed

    private void tf_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_apellidosActionPerformed

    private void tf_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_direccionActionPerformed

    private void tf_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefonoActionPerformed

    private void tf_fdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fdnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fdnActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
       // TODO add your handling code here:
        cliente.setNit(this.tf_nit.getText());
       cliente.setNombres(this.tf_nombres.getText());
       cliente.setApellidos(this.tf_apellidos.getText());
       cliente.setDireccion(this.tf_direccion.getText());
       cliente.setTelefono(this.tf_telefono.getText());
        cliente.setFecha(this.tf_fdn.getText());
       
       String datos[] = {cliente.getNit(),cliente.getNombres(),cliente.getApellidos(),cliente.getDireccion(),cliente.getTelefono(), cliente.getFecha()};
       tbl_model.addRow(datos);
       tf_nit.setText("");
    tf_nombres.setText("");
    tf_apellidos.setText("");
    tf_direccion.setText("");
    tf_telefono.setText("");
     tf_fdn.setText("");
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
    int selectedRow = tbl_clientes.getSelectedRow();
    if (selectedRow >= 0) {
        cliente = new Cliente(tf_nit.getText(), tf_nombres.getText(), tf_apellidos.getText(), tf_direccion.getText(), tf_telefono.getText(), tf_fdn.getText());
        cliente.actualizar(); // Llama al método modificar de tu clase Cliente si es necesario

        // Actualiza los valores en la tabla
        tbl_model.setValueAt(cliente.getNit(), selectedRow, 0);
        tbl_model.setValueAt(cliente.getNombres(), selectedRow, 1);
        tbl_model.setValueAt(cliente.getApellidos(), selectedRow, 2);
        tbl_model.setValueAt(cliente.getDireccion(), selectedRow, 3);
        tbl_model.setValueAt(cliente.getTelefono(), selectedRow, 4);
        tbl_model.setValueAt(cliente.getFecha(), selectedRow, 5);
    } else {
        // No hay ninguna fila seleccionada, maneja este caso si es necesario
    }
    }//GEN-LAST:event_btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fdn;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_titulo_clientes;
    private javax.swing.JLabel lbl_titulo_empleados;
    private javax.swing.JPanel pn_clientes;
    private javax.swing.JPanel pn_empleados;
    private javax.swing.JScrollPane spn_tabla;
    private javax.swing.JTable tbl_clientes;
    private javax.swing.JTextField tf_apellidos;
    private javax.swing.JTextField tf_direccion;
    private javax.swing.JTextField tf_fdn;
    private javax.swing.JTextField tf_nit;
    private javax.swing.JTextField tf_nombres;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTabbedPane tp_principal;
    // End of variables declaration//GEN-END:variables
}
